name: docs
on:
    push:
        branches:
            - main
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --user --no-cache-dir Cython
                  pip install --user -r requirements.txt -r requirements_dev.txt
                  pip install .
            - name: Discover typos with codespell
              run: |
                  codespell --skip="*.csv,*.geojson,*.json,*.js,*.html,*cff,./.git" --ignore-words-list="aci,hist"
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
            - run: mkdocs gh-deploy --force
