name: Publish to GitHub Pages

on:
  push:
    branches:
      - none

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Dependencies
        run: |
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
      - name: Sphinx build
        shell: bash -l {0}
        run: |
          sphinx-build docs _build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          enable_jekyll: false
